#!/usr/bin/env bash
# Usage: jr md5 <file>
# Summary: Returns an MD5 digest of a file
set -e
[ -n "$JR_DEBUG" ] && set -x

banner()  { echo "-----> $*" ; }
info()    { echo "       $*" ; }
warn()    { echo ">>>>>> $*" >&2 ; }

file="$1"

if [ ! -f "$file" ] ; then
  warn "File $file does not exist"
  exit 1
fi

"$(jr-ruby-binpath)/ruby" -rdigest -e "puts Digest::MD5.hexdigest(IO.read('$file'))"
