#!/usr/bin/env bash
# Usage: jr suite-prepare <plugin>
set -e
[ -n "$JR_DEBUG" ] && set -x

log_detail()  { echo "       $*" ; }

suite="$1"
prepare_script="$(jr-suitepath $suite)/prepare.sh"
prepare_recipe="$(jr-suitepath $suite)/prepare_recipe.rb"

if [ -x "$prepare_script" ] ; then
  log_detail "Preparing $plugin suite with $prepare_script"
  "$prepare_script"
fi

if [ -f "$prepare_recipe" ] ; then
  log_detail "Preparing $plugin suite with $prepare_recipe"
  jr-chef-apply "$prepare_recipe"
fi
