#!/usr/bin/env bash
# Usage: jr test
# Summary: Runs all test suites
set -e
[ -n "$JR_DEBUG" ] && set -x

banner()  { echo "-----> $*" ; }
info()    { echo "       $*" ; }
warn()    { echo ">>>>>> $*" >&2 ; }

for plugin in $(jr-list) ; do
  banner "Running $plugin test suite"
  jr-$plugin
done
