#!/usr/bin/env bash
# Usage: jr update
# Summary: Updates the jr codebase to latest release
set -e
[ -n "$JR_DEBUG" ] && set -x

log_heading() { echo "-----> $*" ; }
log_detail()  { echo "       $*" ; }
warn()        { echo ">>>>>> $*" >&2 ; }

url="https://raw.github.com/jamie-ci/jr/go"
tmpdir="/tmp/jr-$$"
script="/tmp/jr-installer-$$"
jr_root="$(jr-root)"

export JR_INSTALL_ROOT="$tmpdir"

jr-download $url $script
jr-ruby "$script"
rm -f "$script"

for d in plugins suites vendor ; do
  cp -rp $jr_root/$d $tmpdir/
done ; unset d

echo rm "$jr_root"
mv "$tmpdir" "$jr_root"

log_detail "Upgrade complete to version $(jr-version --bare)"
