#!/usr/bin/env bash
# Usage: jr version [--bare]
# Summary: Displays the version of jr
set -e
[ -n "$JR_DEBUG" ] && set -x

version="$(cat $(jr-root)/VERSION)"

if [ "$1" == "--bare" ] ; then
  echo "$version"
else
  echo "jr v$version"
fi
