#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _KB_ROOT="$(abs_dirname "$libexec_path")"

for plugin_bin in "${_KB_ROOT}/plugins/"*/bin; do
  libexec_path="${libexec_path}:${plugin_bin}"
done
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec kb-help
  ;;
* )
  command_path="$(command -v "kb-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "kb: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
