#!/usr/bin/env ruby
# Usage: kb github-tags <user> <repo>

require 'chef/rest'

user, repo, splat = ARGV
url = "http://kbr.nichol.ca/tags/#{user}/#{repo}"

EXCEPTIONS = [ SocketError, Errno::ECONNREFUSED, Timeout::Error,
  Net::HTTPFatalError, Net::HTTPServerException ]

begin
  puts Chef::REST.new(url, nil, nil, {}).get_rest(url, false, {})
rescue *EXCEPTIONS => e
  if e.message == %{404 "Not Found"}
    puts "master"
  else
    abort "Could not access #{url} (#{e.message})"
  end
end
