#!/usr/bin/env ruby
# Usage: kb github-tags <user> <repo>

require 'chef/rest'

user, repo, splat = ARGV
url = "https://api.github.com/repos/#{user}/#{repo}/git/refs/tags"

EXCEPTIONS = [ SocketError, Errno::ECONNREFUSED, Timeout::Error,
  Net::HTTPFatalError, Net::HTTPServerException ]

begin
  rest = Chef::REST.new(url, nil, nil, {})
  puts rest.get_rest(url, false, {}).map { |t| t["ref"].split("/").last }.sort
rescue *EXCEPTIONS => e
  if e.message == %{404 "Not Found"}
    puts "master"
  else
    abort "Could not access #{url} (#{e.message})"
  end
end
