#!/usr/bin/env bash
# Usage: kb install <plugin>
# Summary: Lists installed plugins
set -e
[ -n "$KB_DEBUG" ] && set -x

plugin_path="$_KB_ROOT/plugins"

for path in "$plugin_path/"*; do
  if [ -d "$path" ]; then
    echo "${path##*/}"
  fi
done
